domain_path: E:\Vitis\FFAT\FFAT_ATTACK\export\FFAT_ATTACK\sw\standalone_psu_cortexa53_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
